[workspace]
members = [
    "matrix_bot",
    "matrix_bot_core",

    # plugins
    "plugins/yande_popular",
    "plugins/webhook",
    "plugins/qbittorrent",
]
resolver = "2"


[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'
panic = "abort"
strip = true
